version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share_it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    build: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share_it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  gateway:
    build: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090